### ISSUE TITLE
1차 QA전 리펙토링

### ISSUE THREAD

**Issue by thyeone** [forfun-flowing/frontend#97]
### 📌 이슈

1차 QA전 리펙토링
### 📝 To-do

- [x] 가치관 선택 각 3개 선택이 필수가 아닌 각 항목당 '최소 1개'로 수정
- [x] 내 키워드 최대 5개까지 선택할 수 있도록 한다.
- [x] 프로필 사진 등록 후 승인 대기 페이지로 이동했을 때 순간적으로 프로필 사진을 참조할 수 없는 현상
- [ ] 가치관 마지막 항목 하트 버튼 클릭 시 애니메이션 먹히는 현상
- [x] 폼 유효성 강화(정규식 처리)
- [x] 승인 대기 페이지 -> 프로필 페이지로 이동했을 때 이전 데이터 값 + 1 되는 현상
